### PR TITLE
Introduces MarkdownHeaderFile/MarkdownFooterFile

### PR DESCRIPTION
**Pull request by netniV**
Improvements over last commit are:

- As the configuration files are the only place these options can be used, there is no security issues by malicious external user.  
- Allows full customisation of HTML rather than limited string usage.  
- Only takes effect if both header and footer file options are specified to ensure that the markdown is properly wrapped.  
- Allows for configuration inheritance

One side point to note is that it does not do any validity checking that the header/footer files make a valid HTML document as that is assumed to be responsibility of the author.

### CODE REVIEW

**Comment by netniV** [comment]
Have you had time to reconsider the viability of merging this yet?  As I said previously, the perceived security threat you raised is non-existent since the configuration only occurs at server config level not htaccess

**Comment by kekePower** [comment]
Hi @netniV Any chance of rebasing this BR? I love it and use it on my system.

**Comment by netniV** [comment]
I can try, it's been so long I honestly got to remember what I did in what place and why.  Fortunately, the initial diff will help but at the moment, work has me mega busy as you can imagine ;-)

**Comment by kekePower** [comment]
> I can try, it's been so long I honestly got to remember what I did in what place and why. Fortunately, the initial diff will help but at the moment, work has me mega busy as you can imagine ;-)

Thanks. I appreciate your efforts.

**Comment by netniV** [comment]
Give that a try.  Seems to be working for me.

**Comment by netniV** [comment]
Not sure if @hamano will ever commit it as we have a difference in opinion over security of it.  Since i'm using the Apache functions to open/read files, I think it's as secure as apache would be itself.

**Comment by kekePower** [comment]
Thanks a lot, @netniV 

The patch applied cleanly and I've got the header and footer working.

I'll now push an update to this package to Mageia with this patch included.

**Comment by hamano** [comment]
@netniV thanks.

**Pull request merged**
